version: '3.8'
services:
  notifications:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - notifications_db

  notifications_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - notifications_db

  notifications_db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: notifications
      MYSQL_notification: notification
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: roott
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
