version: '2'
services:
  mysql:
    image: mysql:5.7.22
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DyATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
