version: '3.8'
services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - users_db

  users_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - users_db

  users_db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: roott
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
